#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#include "freertos/FreeRTOS.h"

#define PROJECT_DEVICE_NAME "adaptive-sampling-node"
#define PROJECT_WIFI_SSID ""
#define PROJECT_WIFI_PASSWORD ""
#define PROJECT_WIFI_MAXIMUM_RETRY 10U
#define PROJECT_DEFAULT_MQTT_BROKER_HOST "broker.local"
#define PROJECT_DEFAULT_MQTT_BROKER_PORT 1883
#define PROJECT_DEFAULT_MQTT_TOPIC "project/" PROJECT_DEVICE_NAME "/aggregate"
#define PROJECT_MQTT_SECURITY_PLAINTEXT 1U
#define PROJECT_MQTT_SECURITY_TLS 2U
#define PROJECT_MQTT_SECURITY_MODE PROJECT_MQTT_SECURITY_PLAINTEXT
#define PROJECT_MQTT_USERNAME ""
#define PROJECT_MQTT_PASSWORD ""
#define PROJECT_MQTT_TLS_COMMON_NAME ""
#define PROJECT_MQTT_TLS_SKIP_COMMON_NAME_CHECK 0U
#define PROJECT_DEFAULT_NTP_SERVER "pool.ntp.org"
#define PROJECT_COMMUNICATION_MODE_MQTT_ONLY 1U
#define PROJECT_COMMUNICATION_MODE_LORAWAN_ONLY 2U
#define PROJECT_COMMUNICATION_MODE_BOTH 3U
#define PROJECT_COMMUNICATION_MODE PROJECT_COMMUNICATION_MODE_BOTH
#define PROJECT_LORAWAN_ENABLE_RADIO_TX 0U
#define PROJECT_LORAWAN_FPORT 1U
#define PROJECT_LORAWAN_UPLINK_TOPIC "ttn/uplink"
#define PROJECT_LORAWAN_DEFAULT_DR 3
#define PROJECT_LORAWAN_TX_DUTY_CYCLE_MS 15000U
#define PROJECT_LORAWAN_ADR_ENABLED 1U
#define PROJECT_LORAWAN_CONFIRMED_UPLINKS 0U
#define PROJECT_LORAWAN_CONFIRMED_TRIALS 4U
#define PROJECT_LORAWAN_USE_CHIP_GENERATED_DEV_EUI 0U
#define PROJECT_LORAWAN_JOIN_EUI_BYTES \
    { 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U }
#define PROJECT_LORAWAN_DEV_EUI_BYTES \
    { 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U }
#define PROJECT_LORAWAN_APP_KEY_BYTES                                                    \
    {                                                                                    \
        0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U,                         \
            0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U                      \
    }
#define PROJECT_LORAWAN_CHANNEL_MASK \
    { 0x00FFU, 0x0000U, 0x0000U, 0x0000U, 0x0000U, 0x0000U }
#define PROJECT_LORAWAN_HELTEC_LICENSE_WORDS \
    { 0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U }
#define PROJECT_LORAWAN_APPLY_HELTEC_LICENSE_AT_BOOT 0U
#define PROJECT_ENABLE_SAMPLING_BENCHMARK 0

#define PROJECT_TWO_PI_F 6.28318530718f

#define PROJECT_SAMPLE_QUEUE_LENGTH 32
#define PROJECT_FFT_QUEUE_LENGTH 8
#define PROJECT_AGGREGATE_QUEUE_LENGTH 8
#define PROJECT_MQTT_QUEUE_LENGTH 8
#define PROJECT_LORAWAN_QUEUE_LENGTH 8

#define PROJECT_TASK_STACK_SIZE 4096
#define PROJECT_LORAWAN_TASK_STACK_SIZE 8192
#define PROJECT_DISPLAY_TASK_STACK_SIZE 3072

#define PROJECT_TASK_PRIORITY_INPUT 6
#define PROJECT_TASK_PRIORITY_PROCESSING 5
#define PROJECT_TASK_PRIORITY_CONTROL 4
#define PROJECT_TASK_PRIORITY_COMM 4
#define PROJECT_TASK_PRIORITY_METRICS 3
#define PROJECT_TASK_PRIORITY_DISPLAY 2

#define PROJECT_INITIAL_SAMPLING_FREQUENCY_HZ 50.0f
#define PROJECT_SIGNAL_PROFILE_CLEAN_REFERENCE 1U
#define PROJECT_SIGNAL_PROFILE_NOISY_REFERENCE 2U
#define PROJECT_SIGNAL_PROFILE_ANOMALY_STRESS 3U
#define PROJECT_SIGNAL_PROFILE PROJECT_SIGNAL_PROFILE_CLEAN_REFERENCE
#define PROJECT_SIGNAL_TERM1_AMPLITUDE 2.0f
#define PROJECT_SIGNAL_TERM1_FREQUENCY_HZ 3.0f
#define PROJECT_SIGNAL_TERM2_AMPLITUDE 4.0f
#define PROJECT_SIGNAL_TERM2_FREQUENCY_HZ 5.0f
#define PROJECT_SIGNAL_NOISE_SIGMA 0.2f
#define PROJECT_SIGNAL_ANOMALY_PROBABILITY 0.02f
#define PROJECT_SIGNAL_ANOMALY_MIN_MAGNITUDE 5.0f
#define PROJECT_SIGNAL_ANOMALY_MAX_MAGNITUDE 15.0f
#define PROJECT_SIGNAL_RANDOM_SEED 0x5A17C3E1U
#define PROJECT_SIGNAL_WINDOW_DURATION_SEC 5U
#define PROJECT_SIGNAL_WINDOW_MAX_SAMPLES 256U
#define PROJECT_SIGNAL_PREVIEW_SAMPLES 5U
#define PROJECT_SIGNAL_INPUT_LOG_INTERVAL 25U
#define PROJECT_FFT_PEAKS_TO_LOG 3U
#define PROJECT_ENABLE_BETTER_SERIAL_PLOTTER 1U
#define PROJECT_BETTER_SERIAL_PLOTTER_SILENCE_INFO_LOGS 1U

#define PROJECT_ENABLE_ADAPTIVE_SAMPLING 1U
#define PROJECT_ADAPTIVE_OVERSAMPLING_FACTOR 8.0f
#define PROJECT_ADAPTIVE_MIN_SAMPLING_FREQUENCY_HZ 20.0f
#define PROJECT_ADAPTIVE_MAX_SAMPLING_FREQUENCY_HZ 50.0f
#define PROJECT_ADAPTIVE_RATE_STEP_HZ 5.0f
#define PROJECT_ADAPTIVE_CHANGE_THRESHOLD_HZ 0.5f

#define PROJECT_BENCHMARK_STAGE_DURATION_MS 4000U
#define PROJECT_BENCHMARK_PROGRESS_REPORT_MS 1000U
#define PROJECT_BENCHMARK_QUEUE_DROP_THRESHOLD 0U
#define PROJECT_BENCHMARK_DEADLINE_MISS_TOLERANCE_US 800U

#define PROJECT_INPUT_HEARTBEAT_MS 20
#define PROJECT_PROCESSING_TIMEOUT_MS 1500
#define PROJECT_CONTROL_HEARTBEAT_MS 4000
#define PROJECT_MQTT_HEARTBEAT_MS 5000
#define PROJECT_LORAWAN_HEARTBEAT_MS 7000
#define PROJECT_METRICS_HEARTBEAT_MS 6000
#define PROJECT_DISPLAY_HEARTBEAT_MS 8000
#define PROJECT_SUPERVISOR_HEARTBEAT_MS 10000

#define PROJECT_EVENT_BOOT_COMPLETE BIT0
#define PROJECT_EVENT_SIGNAL_INPUT_READY BIT1
#define PROJECT_EVENT_SIGNAL_PROCESSING_READY BIT2
#define PROJECT_EVENT_SAMPLING_CONTROL_READY BIT3
#define PROJECT_EVENT_MQTT_READY BIT4
#define PROJECT_EVENT_LORAWAN_READY BIT5
#define PROJECT_EVENT_METRICS_READY BIT6
#define PROJECT_EVENT_DISPLAY_READY BIT7

#if defined(__has_include)
#if __has_include("project_config_local.h")
#include "project_config_local.h"
#endif
#endif

#endif
