#ifndef PROJECT_CONFIG_LOCAL_EXAMPLE_H
#define PROJECT_CONFIG_LOCAL_EXAMPLE_H

#undef PROJECT_WIFI_SSID
#define PROJECT_WIFI_SSID "YOUR_WIFI_SSID"

#undef PROJECT_WIFI_PASSWORD
#define PROJECT_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#undef PROJECT_DEFAULT_MQTT_BROKER_HOST
#define PROJECT_DEFAULT_MQTT_BROKER_HOST "YOUR_BROKER_HOST"

#undef PROJECT_DEFAULT_MQTT_BROKER_PORT
#define PROJECT_DEFAULT_MQTT_BROKER_PORT 1883

#undef PROJECT_MQTT_SECURITY_MODE
#define PROJECT_MQTT_SECURITY_MODE PROJECT_MQTT_SECURITY_PLAINTEXT

#undef PROJECT_MQTT_USERNAME
#define PROJECT_MQTT_USERNAME ""

#undef PROJECT_MQTT_PASSWORD
#define PROJECT_MQTT_PASSWORD ""

#undef PROJECT_MQTT_TLS_COMMON_NAME
#define PROJECT_MQTT_TLS_COMMON_NAME ""

#undef PROJECT_MQTT_TLS_SKIP_COMMON_NAME_CHECK
#define PROJECT_MQTT_TLS_SKIP_COMMON_NAME_CHECK 0U

#endif
