[platformio]
src_dir = main
include_dir = include

[env:heltec_wifi_lora_32_V3]
platform = espressif32
framework = espidf
board = heltec_wifi_lora_32_V3
board_build.partitions = partitions_heltec_8mb.csv
monitor_speed = 115200
build_unflags =
    -Werror=all
build_flags =
    -Wno-error=format
